const levels=[
{title:"La primera llave",difficulty:2,hint:"No es una palabra cualquiera. Entre ustedes empezó a significar algo enorme.",render(){return `<p class="level-intro">La primera llave está incompleta. No basta con adivinar una palabra: tienes que reconocer una forma de nombrar lo que a veces “mundo” ya no alcanza a explicar.</p><div class="challenge-box"><div class="code">M _ &nbsp; C _ S M _ S</div><input id="answer" type="text" autocomplete="off" placeholder="Escribe la frase completa"><div class="action-row"><button class="primary" onclick="checkText(0,'mi cosmos')">Comprobar</button></div><div id="feedback" class="feedback"></div></div>`},reward:"Una palabra suya quedó convertida en constelación: “mi cosmos”."},
{title:"El mensaje numerado",difficulty:3,hint:"Usa A=1, B=2, C=3… pero no olvides los espacios.",render(){return `<p class="level-intro">Los números también pueden hablar. Descifra la frase:</p><div class="challenge-box"><div class="code">3-21-9-4-1-20-5 / 13-21-3-8-15</div><input id="answer" type="text" autocomplete="off" placeholder="¿Qué dice?"><div class="action-row"><button class="primary" onclick="checkText(1,'cuidate mucho')">Comprobar</button></div><div id="feedback" class="feedback"></div></div>`},reward:"Una frase que se repite porque el cariño también se nota en el cuidado."},
{title:"La secuencia invisible",difficulty:3,hint:"Piensa en el orden natural de un día juntos, no en números.",render(){const o=["Bonita noche","Buenos días","¿Cómo estás?","Cuídate mucho"];return `<p class="level-intro">Ordena estos momentos como si fueran parte de un día. Toca los cuatro en el orden que te parezca más natural.</p><div class="sequence-grid">${o.map(x=>`<button class="tile" data-v="${x}" onclick="seqPick(this)">${x}</button>`).join("")}</div><div class="sort-zone" id="sequenceZone"></div><div class="action-row"><button class="primary" onclick="checkSequence()">Comprobar orden</button><button class="ghost" onclick="resetSequence()">Reiniciar</button></div><div id="feedback" class="feedback"></div>`},reward:"Lo cotidiano también cuenta una historia cuando viene de alguien especial."},
{title:"La memoria de las estrellas",difficulty:4,hint:"No necesitas rapidez. Mira, recuerda y empareja.",render(){const p=seededShuffle(["☀️","🌙","💛","✨","☀️","🌙","💛","✨"],42);return `<p class="level-intro">Encuentra las cuatro parejas. Aquí no gana quien corre: gana quien observa.</p><div class="memory-grid" id="memoryGrid">${p.map((v,i)=>`<button class="memory-card" data-v="${v}" data-i="${i}" onclick="flipMemory(this)">✦</button>`).join("")}</div><div id="feedback" class="feedback">Parejas encontradas: <span id="pairCount">0</span>/4</div>`},reward:"Observar también es una forma de querer: notar lo que otros dejarían pasar."},
{title:"El idioma de nosotros",difficulty:4,hint:"Una de estas expresiones aparece como algo muy suyo. No es 'mi mundo'.",render(){const o=["Mi universo entero","Mi cosmos","Mi estrella favorita","Mi planeta"];return `<p class="level-intro">Entre palabras bonitas, una terminó tomando un significado especial. Elige la que mejor representa esa forma de nombrarse.</p><div class="options">${o.map((x,i)=>`<button class="option" onclick="checkOption(this,${i===1},4)">${x}</button>`).join("")}</div><div id="feedback" class="feedback"></div>`},reward:"Hay palabras que cualquiera puede decir. Y hay palabras que, entre dos personas, cambian para siempre."},
{title:"El cifrado de la heroína",difficulty:5,hint:"Cada símbolo representa una letra. Usa la clave visual y arma una frase de tres palabras.",render(){return `<p class="level-intro">Esta vez no basta con leer. Usa la clave:</p><div class="challenge-box"><div class="code">☾=E &nbsp; ✦=R &nbsp; ♡=S &nbsp; ☀=M &nbsp; ◇=I &nbsp; ♧=H &nbsp; △=O &nbsp; ○=N &nbsp; ☆=A</div><div class="code" style="margin-top:18px">☾ ✦ ♡ / ☀ ◇ / ♧ ☾ ✦ △ ◇ ○ ☆</div><input id="answer" type="text" autocomplete="off" placeholder="Descifra la frase"><div class="action-row"><button class="primary" onclick="checkText(5,'eres mi heroina')">Comprobar</button></div><div id="feedback" class="feedback"></div></div>`},reward:"La respuesta estaba en los símbolos, pero la idea ya estaba en el corazón: eres mi heroína."},
{title:"El camino correcto",difficulty:4,hint:"Busca el camino que habla de construir, no de escapar ni de adivinar.",render(){return `<p class="level-intro">Son casi las doce. Frente a ti aparecen tres caminos. Solo uno representa la forma en que quiero vivir esto contigo.</p><div class="path-grid"><div class="path-card" onclick="pathChoice(this,false)"><h4>La puerta del silencio</h4><p>No hablar, esperar y suponer que el tiempo resuelva todo.</p></div><div class="path-card" onclick="pathChoice(this,true)"><h4>La ruta de construir</h4><p>Hablar, aprender, cuidar, mejorar y seguir demostrando con hechos.</p></div><div class="path-card" onclick="pathChoice(this,false)"><h4>La escalera de la suerte</h4><p>Confiar en que todo funcione sin hacer nada diferente.</p></div></div><div id="feedback" class="feedback"></div>`},reward:"No quiero que lo nuestro dependa de suerte. Quiero construirlo contigo."},
{title:"Las tres palabras",difficulty:5,hint:"Las tres palabras no describen objetos. Describen lo que debe sostener una relación.",render(){const w=["DISTANCIA","CONFIANZA","RUIDO","CUIDADO","PRISA","AMOR","MIEDO","DUDA"];return `<p class="level-intro">Elige exactamente tres palabras que, juntas, formen la base del mensaje que quiero dejarte hoy.</p><div class="sequence-grid">${w.map(x=>`<button class="tile" data-v="${x}" onclick="multiPick(this)">${x}</button>`).join("")}</div><div class="action-row"><button class="primary" onclick="checkThree()">Comprobar</button></div><div id="feedback" class="feedback"></div>`},reward:"Confianza, cuidado y amor: tres palabras simples, pero enormes cuando son constantes."},
{title:"La frase escondida",difficulty:5,hint:"No intentes leerla como una oración normal. Hay caracteres de relleno intercalados.",render(){return `<p class="level-intro">Este mensaje tiene ruido alrededor. Debes encontrar la frase escondida.</p><div class="challenge-box"><div class="code">PZIQEWNXSXO / EBNQ / TKIQ / DQIXA / AQ / DQIXA</div><p style="color:var(--muted);line-height:1.6">Regla: en cada bloque, conserva una letra y descarta la siguiente, comenzando por la primera.</p><input id="answer" type="text" autocomplete="off" placeholder="Escribe la frase"><div class="action-row"><button class="primary" onclick="checkText(8,'pienso en ti dia a dia')">Comprobar</button></div><div id="feedback" class="feedback"></div></div>`},reward:"Aunque haya ruido, una idea sigue apareciendo: pienso en ti día a día."},
{title:"El corazón",difficulty:5,hint:"La respuesta final no está en una clave. Está en el nombre de la persona para quien existe todo esto.",render(){return `<div class="final-heart">💛</div><p class="level-intro" style="text-align:center">Llegaste hasta aquí. La última puerta no se abre con números, símbolos ni memoria.</p><div class="challenge-box"><p style="text-align:center;font-size:1.18rem;line-height:1.7">“Para abrir el último nivel necesitas la única respuesta que nunca te pediría adivinar.”</p><input id="answer" type="text" autocomplete="off" placeholder="¿Quién es mi heroína?"><div class="action-row" style="justify-content:center"><button class="primary" onclick="checkFinal()">Abrir el corazón</button></div><div id="feedback" class="feedback" style="text-align:center"></div></div>`},reward:"Llegaste al final, pero en realidad no necesitabas superar diez pruebas para llegar a mi corazón. Ya estabas ahí."}
];
let currentLevel=0,progress=Number(localStorage.getItem("cynthiaProgress")||0),seq=[],memoryOpen=[],memoryMatched=0,multi=new Set();
const levelTitle=document.getElementById("levelTitle"),levelNumber=document.getElementById("levelNumber"),difficulty=document.getElementById("difficulty"),levelBody=document.getElementById("levelBody"),hintBtn=document.getElementById("hintBtn"),hintText=document.getElementById("hintText"),unlockOverlay=document.getElementById("unlockOverlay"),unlockTitle=document.getElementById("unlockTitle"),unlockReward=document.getElementById("unlockReward");
document.getElementById("beginBtn").onclick=()=>{document.getElementById("intro").classList.add("hidden");renderMap();if(progress>=10)showFinalMessage();else loadLevel(Math.min(progress,9));};
document.getElementById("nextBtn").onclick=()=>{unlockOverlay.classList.add("hidden");if(progress>=10){showFinalMessage();return;}loadLevel(Math.min(progress,9));};
document.getElementById("resetBtn").onclick=()=>{if(confirm("¿Reiniciar los 10 niveles y borrar el progreso guardado?")){localStorage.removeItem("cynthiaProgress");progress=0;currentLevel=0;renderMap();loadLevel(0);}};
hintBtn.onclick=()=>{hintText.textContent=levels[currentLevel].hint;};
function normalize(s){return(s||"").toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9 ]/g,"").replace(/\s+/g," ").trim()}
function updateProgress(){document.getElementById("progressText").textContent=`${progress} / 10`;document.getElementById("progressBar").style.width=`${progress*10}%`}
function renderMap(){const map=document.getElementById("map"),pos=[[12,17],[42,9],[73,17],[24,34],[58,31],[82,44],[13,58],[43,55],[69,69],[36,80]];map.innerHTML=levels.map((l,i)=>{const u=i<=progress,cls=`${u?"unlocked":"locked"} ${i===currentLevel?"active":""}`;return `<button class="star-node ${cls}" style="left:${pos[i][0]}%;top:${pos[i][1]}%" data-label="${i+1}" onclick="mapGo(${i})" ${u?"":"disabled"}>${i+1}</button>`}).join("");updateProgress()}
function mapGo(i){if(i<progress)loadLevel(i);else if(i===progress&&progress<10)loadLevel(i)}
function loadLevel(i){currentLevel=i;seq=[];memoryOpen=[];memoryMatched=0;multi=new Set();levelNumber.textContent=`NIVEL ${i+1}`;levelTitle.textContent=levels[i].title;difficulty.textContent="✦".repeat(levels[i].difficulty)+"☆".repeat(5-levels[i].difficulty);hintText.textContent="";levelBody.innerHTML=levels[i].render();renderMap();document.getElementById("gameArea").scrollIntoView({behavior:"smooth",block:"start"})}
function feedback(msg,good=false){const el=document.getElementById("feedback");if(el){el.textContent=msg;el.style.color=good?"#c8ffd9":"#ffe3a0"}}
function completeLevel(i){if(i===progress){progress++;localStorage.setItem("cynthiaProgress",String(progress))}renderMap();unlockTitle.textContent=i===9?"El corazón está abierto":`Estrella ${i+1} desbloqueada`;unlockReward.textContent=levels[i].reward;unlockOverlay.classList.remove("hidden");burst()}
function checkText(i,expected){const val=normalize(document.getElementById("answer").value);if(val===normalize(expected)){feedback("Correcto ✨",true);setTimeout(()=>completeLevel(i),350)}else feedback("Todavía no. Mira la pista o vuelve a observar el patrón.")}
function checkOption(btn,correct,i){document.querySelectorAll(".option").forEach(x=>x.classList.remove("correct","wrong"));if(correct){btn.classList.add("correct");feedback("Esa es ✨",true);setTimeout(()=>completeLevel(i),400)}else{btn.classList.add("wrong");feedback("No es esa. Piensa en una palabra que ustedes hicieron especial.")}}
function seqPick(btn){if(btn.classList.contains("selected"))return;btn.classList.add("selected");seq.push(btn.dataset.v);document.getElementById("sequenceZone").innerHTML=seq.map((x,i)=>`<span class="sort-item">${i+1}. ${x}</span>`).join("")}
function resetSequence(){seq=[];document.querySelectorAll(".tile").forEach(x=>x.classList.remove("selected"));document.getElementById("sequenceZone").innerHTML="";feedback("")}
function checkSequence(){const e=["Buenos días","¿Cómo estás?","Cuídate mucho","Bonita noche"];if(seq.length===4&&seq.every((v,i)=>v===e[i])){feedback("Orden correcto ✨",true);setTimeout(()=>completeLevel(2),350)}else feedback("Casi. Piensa en cómo transcurre un día desde la mañana hasta cerrar la noche.")}
function seededShuffle(arr,seed){let a=[...arr],x=seed;for(let i=a.length-1;i>0;i--){x=(x*9301+49297)%233280;const j=Math.floor((x/233280)*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function flipMemory(btn){if(btn.classList.contains("revealed")||memoryOpen.length===2)return;btn.classList.add("revealed");btn.textContent=btn.dataset.v;memoryOpen.push(btn);if(memoryOpen.length===2){setTimeout(()=>{const[a,b]=memoryOpen;if(a.dataset.v===b.dataset.v){a.disabled=b.disabled=true;memoryMatched++;document.getElementById("pairCount").textContent=memoryMatched;if(memoryMatched===4)setTimeout(()=>completeLevel(3),350)}else{a.classList.remove("revealed");b.classList.remove("revealed");a.textContent=b.textContent="✦"}memoryOpen=[]},700)}}
function pathChoice(card,ok){document.querySelectorAll(".path-card").forEach(x=>x.style.borderColor="rgba(255,255,255,.11)");if(ok){card.style.borderColor="rgba(126,233,168,.7)";feedback("Ese es el camino ✨",true);setTimeout(()=>completeLevel(6),350)}else{card.style.borderColor="rgba(255,122,150,.7)";feedback("Ese camino no representa lo que quiero construir contigo.")}}
function multiPick(btn){const v=btn.dataset.v;if(multi.has(v)){multi.delete(v);btn.classList.remove("selected")}else{if(multi.size>=3)return;multi.add(v);btn.classList.add("selected")}}
function checkThree(){const e=["CONFIANZA","CUIDADO","AMOR"];if(multi.size===3&&e.every(x=>multi.has(x))){feedback("Las tres sostienen el mensaje ✨",true);setTimeout(()=>completeLevel(7),350)}else feedback("No. Busca tres palabras que hablen de construir algo sano y bonito.")}
function checkFinal(){const val=normalize(document.getElementById("answer").value);if(val==="cynthia"){feedback("Siempre tú. ✨",true);setTimeout(()=>completeLevel(9),350)}else feedback("La respuesta tiene nombre propio.")}
function showFinalMessage(){levelNumber.textContent="FINAL";levelTitle.textContent="Ya estabas aquí";difficulty.textContent="★★★★★";hintText.textContent="";levelBody.innerHTML=`<div class="final-heart">💛</div><p class="level-intro" style="text-align:center;font-size:1.2rem">Llegaste hasta aquí, mi amor. Pero la verdad es que nunca necesitaste superar diez pruebas para llegar a mi corazón. <strong>Ya estabas ahí.</strong></p><div class="challenge-box"><p style="font-size:1.12rem;line-height:1.85;text-align:center">Gracias por tus buenos días, tus bonitas noches, por cada “cuídate mucho”, por escucharme, por estar pendiente de mí, por tu cariño, tu tiempo y tu atención.<br><br>Yo sigo pensando en ti día a día. Sigo queriendo aprender, mejorar, cuidar lo nuestro y pelear de la manera correcta: no contra ti, sino <strong>por nosotros</strong>.<br><br>Eres mi heroína, mi cosmos, mi lugar seguro y mi amor bonito.<br><br>— Juan Carlos</p></div>`;renderMap();document.getElementById("gameArea").scrollIntoView({behavior:"smooth"})}
function burst(){for(let i=0;i<22;i++){const e=document.createElement("div");e.textContent=i%3===0?"♡":"✦";e.style.cssText=`position:fixed;z-index:80;left:${45+Math.random()*10}vw;top:${46+Math.random()*8}vh;color:${i%2?"#f4cf7f":"#ffd6e8"};font-size:${14+Math.random()*18}px;pointer-events:none;transition:1.4s ease;`;document.body.appendChild(e);requestAnimationFrame(()=>{e.style.transform=`translate(${(Math.random()-.5)*260}px,${-80-Math.random()*180}px) rotate(${Math.random()*100}deg)`;e.style.opacity=0});setTimeout(()=>e.remove(),1500)}}
const canvas=document.getElementById("stars"),ctx=canvas.getContext("2d");let W,H,stars=[];function resize(){const dpr=Math.min(devicePixelRatio||1,2);W=canvas.width=innerWidth*dpr;H=canvas.height=innerHeight*dpr;canvas.style.width=innerWidth+"px";canvas.style.height=innerHeight+"px";stars=Array.from({length:Math.max(70,Math.floor(innerWidth*innerHeight/9000))},()=>({x:Math.random()*W,y:Math.random()*H,r:Math.random()*1.8+.4,a:Math.random()*.8+.2,s:Math.random()*.012+.004}))}function draw(){ctx.clearRect(0,0,W,H);for(const s of stars){s.a+=s.s*(Math.random()>.5?1:-1);s.a=Math.max(.15,Math.min(1,s.a));ctx.beginPath();ctx.fillStyle=`rgba(255,255,255,${s.a})`;ctx.arc(s.x,s.y,s.r,0,Math.PI*2);ctx.fill()}requestAnimationFrame(draw)}addEventListener("resize",resize);resize();draw();renderMap();updateProgress();
